spring:
  #redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 2
    host: 127.0.0.1
    port: 6379
    password: zhangjun
      # 集群环境打开下面注释，单机不需要打开
#      cluster:
#        ##集群信息
#        nodes: 192.168.234.128:8001,192.168.234.128:8002,192.168.234.128:8003,192.168.234.128:8004,192.168.234.128:8005,192.168.234.128:8006,192.168.234.128:8007,192.168.234.128:8008
#        ##默认值是5 一般当此值设置过大时，容易报：Too many Cluster redirections
#        maxRedirects: 3
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认为8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认为8
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认为8
        max-idle: 8
        # 连接池中的最小空闲连接 默认为0
        min-idle: 0
      # 连接超时时间（毫秒）默认是2000ms
      timeout: 2000ms